baseURL = 'https://ianmyjer.com/'
languageCode = 'en-us'
title = 'Ian Myjer'
theme = 'hyde'

[Menus]
main = [
    { Name = "Github", URL = "https://github.com/enmyj" },
    { Name = "LinkedIn", URL = "https://www.linkedin.com/in/ian-myjer/" },
]
[params]
description = "Welcome!"
